name: "Install fonts via fontsource"

inputs:
  font-name:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v7
      id: font-key
      env:
        FONT_NAME: ${{ inputs.font-name }}
      with:
        script: |
          return process.env.FONT_NAME.replaceAll(" ", "-").toLowerCase()
        result-encoding: string
    - shell: bash
      working-directory: ${{ runner.temp }}
      env:
        FONT_KEY: ${{ steps.font-key.outputs.result }}
      run: |
        wget -O ./$FONT_KEY.zip https://api.fontsource.org/v1/download/$FONT_KEY
        unzip ./$FONT_KEY.zip -d ./$FONT_KEY
        rm ./$FONT_KEY/ttf/$FONT_KEY-[0-9]*
        mv ./$FONT_KEY/ttf /usr/share/fonts/$FONT_KEY
        fc-cache -fv
        rm ./$FONT_KEY.zip
        rm -r ./$FONT_KEY
